-- Deterministic seed data.
--
-- CORE OPERATION 0A — create deterministic walkthrough data.
-- WALKTHROUGH: 60 patients produce 92 study enrollments (60 daily + 20 weekly
-- + 12 acute), which become 60 initial patient-level jobs after coalescing.
-- These population counts are demo choices, not packet requirements.
--
-- Everything below is generated by modulo arithmetic rather than randomness, so
-- the demo and the tests observe the same population every run.

BEGIN;

-- ---------------------------------------------------------------------------
-- EHR endpoints, with the rate limits quoted in the exercise.
-- ---------------------------------------------------------------------------
INSERT INTO ehr_endpoints (key, display_name, rate_limit_per_min) VALUES
  ('epic',              'Epic',                   100),
  ('cerner',            'Cerner',                  30),
  ('regional-northwest','Regional Health NW',      30);

-- Token buckets start full: capacity is one minute of allowance, which is the
-- burst a caller may spend before being throttled to the sustained rate.
INSERT INTO rate_limit_buckets (endpoint_id, tokens, capacity, refill_per_sec)
SELECT id, rate_limit_per_min, rate_limit_per_min, rate_limit_per_min / 60.0
FROM ehr_endpoints;

-- ---------------------------------------------------------------------------
-- Studies. Three refresh cadences and three urgency levels.
--
-- 'acute-monitoring' has a deliberately short interval so that `npm start`
-- shows recurring scheduling within a demo session rather than one initial
-- wave followed by 24 hours of silence. The daily and weekly studies are the
-- realistic cases.
-- ---------------------------------------------------------------------------
INSERT INTO studies (name, refresh_interval, base_priority) VALUES
  ('cardiology-longitudinal', interval '1 day',     100),
  ('oncology-weekly-panel',   interval '7 days',    120),
  ('acute-monitoring',        interval '2 minutes', 200);

-- ---------------------------------------------------------------------------
-- 60 patients.
-- ---------------------------------------------------------------------------
INSERT INTO patients (external_ref)
SELECT 'pat-' || lpad(n::text, 4, '0') FROM generate_series(1, 60) AS n;

-- Enrollments:
--   every patient  -> cardiology-longitudinal (daily)
--   id % 3 = 0     -> oncology-weekly-panel   (weekly, higher priority)
--   id % 5 = 0     -> acute-monitoring        (2 min, highest priority)
--
-- Patients matching more than one rule are the interesting case: their due
-- studies coalesce into a single refresh instead of one call per study.
INSERT INTO patient_studies (patient_id, study_id, consent_expires_at)
SELECT p.id, s.id,
       -- Every 11th patient has consent lapsing inside the urgency window,
       -- which the scheduler turns into a priority boost.
       CASE WHEN p.id % 11 = 0 THEN now() + interval '3 days' END
FROM patients p
JOIN studies s ON
     s.name = 'cardiology-longitudinal'
  OR (s.name = 'oncology-weekly-panel' AND p.id % 3 = 0)
  OR (s.name = 'acute-monitoring'      AND p.id % 5 = 0);

-- Endpoint associations:
--   every patient -> epic
--   id % 2 = 0    -> cerner
--   id % 7 = 0    -> regional-northwest
--
-- Patients on more than one endpoint are throttled by their SLOWEST endpoint,
-- because one patient-level call has to consume budget from all of them.
INSERT INTO patient_endpoints (patient_id, endpoint_id)
SELECT p.id, e.id
FROM patients p
JOIN ehr_endpoints e ON
     e.key = 'epic'
  OR (e.key = 'cerner'             AND p.id % 2 = 0)
  OR (e.key = 'regional-northwest' AND p.id % 7 = 0);

COMMIT;
